Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -111,4 +111,46 @@ jobs:
           kubectl rollout status deployment/hello-gitops-green -n hello-gitops-new --timeout=300s
         else
           echo "Waiting for Blue deployment rollout"
-          kubectl rollout status deployment/hello-gitops-blue -n hello-gitops
+          kubectl rollout status deployment/hello-gitops-blue -n hello-gitops-new --timeout=300s
+        fi
+
+    - name: Switch traffic
+      run: |
+        if [[ "${{ env.next_version }}" == "green" ]]; then
+          echo "Switching traffic to Green"
+          kubectl patch service hello-gitops -n hello-gitops-new -p '{"spec":{"selector":{"app":"hello-gitops","version":"green"}}}'
+        else
+          echo "Switching traffic to Blue"
+          kubectl patch service hello-gitops -n hello-gitops-new -p '{"spec":{"selector":{"app":"hello-gitops","version":"blue"}}}'
+        fi
+
+    - name: Validate traffic switch
+      run: |
+        service=$(kubectl get svc hello-gitops -n hello-gitops-new -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+        echo "Testing application at $service"
+        for i in {1..10}; do
+          curl -s "http://$service" && echo "Success!" && exit 0 || echo "Retrying..."
+          sleep 5
+        done
+        echo "Error: Application did not respond as expected."
+        exit 1
+
+    - name: Cleanup old deployment
+      run: |
+        if [[ "${{ env.next_version }}" == "green" ]]; then
+          echo "Checking for Blue deployment"
+          if kubectl get deployment hello-gitops-blue -n hello-gitops-new; then
+            echo "Deleting Blue deployment"
+            kubectl delete deployment hello-gitops-blue -n hello-gitops-new
+          else
+            echo "No Blue deployment found to delete"
+          fi
+        else
+          echo "Checking for Green deployment"
+          if kubectl get deployment hello-gitops-green -n hello-gitops-new; then
+            echo "Deleting Green deployment"
+            kubectl delete deployment hello-gitops-green -n hello-gitops-new
+          else
+            echo "No Green deployment found to delete"
+          fi
+        fi
